### ISSUE TITLE
Remove all of an item in cart

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#109]
make it possible to remove all of an item with one click from the cart view

**Comment by bglusman** [comment]
To clarify, there's already this button in the ordering pane but if it's in cart and you've switched credit types, there's no way to remove from cart directly

**Comment by aaronshim** [comment]
Is this being looked at? If not, could I try taking a look at it for Hacktoberfest? Thanks so much!

**Comment by bglusman** [comment]
@aaronshim that would be awesome, please take a look and let me know if any questions or problems!

**Comment by fcapovilla** [comment]
Is this a duplicate of issue #118? If it is, can we close this issue?

**Comment by bglusman** [comment]
oh it totally is good catch... sigh...
