### ISSUE TITLE
It's possible to remove items from cart

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#118]
Place an x in the far right side of the cart so that guests can remove all of an item from the cart without having to find the item in the ordering menu

**Comment by fcapovilla** [comment]
I created a pull request to fix this issue.
I reused the garbage can SVG from the ordering menu instead of using an "x" to stay visually consistent.

**Comment by bglusman** [comment]
Awesome, thanks so much again!  I'd like to extract those SVG's to asset files or partials to make reuse easier (I think there's a ticket for that?) but can do that seperately unless you have time and want to tackle that also while touching one.

**Comment by fcapovilla** [comment]
I've found the ticket : #106 
I'll look into it and add my fix in the current pull request.
Or do you want me to create a different pull request for that?

**Comment by bglusman** [comment]
Whatever's easiest for you :-)

**Comment by fcapovilla** [comment]
The pull request was merged. Can we close this ticket?
