### ISSUE TITLE
Enable cron

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#141]
Currently, user credit quantities do not refresh. We need to have the option to update by different time periods.

**Comment by bglusman** [comment]
credit types have two relevant fields,   :credits_per_period and  :period_name... period name should probably be an enum not a string, and could probably be weekly, bi-weekly or monthly at a guess, and some background task needs to run periodically or check every day at midnight which user credits are currentlow lower than the credits_per_period for their associated credit_type... probably at that moment any that are lower get reset to the credits_per_period value, though there's a product/business decision perhaps to be made of whether that should be unconditional or needs a configuration option that adds that many credits to the total if below the credits_per_period, so essentially users can roll over credits to up to 2*credits_per_period - 1.  

This ticket will probably involve adding https://github.com/c-rack/quantum-elixir to the project and configuring it as well a new module responsible for performing these checks/changes whenever run

**Comment by bglusman** [comment]
This may help picking cron values for quantum http://corntab.com
Possibly it should only run once a week to be less confusing/less sensitive  to exact sign up date etc?  Possibly this will be the cron value for that `1 0 */7 * *`

**Comment by bglusman** [comment]
This is resolved by Heroku scheduler + mix task for now
