### ISSUE TITLE
Improve image quality of thumbnail images

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#170]
This is likely a pretty simple fix. Imagemagick is used to handle the compression etc.

*Minimum acceptance criteria*
- [ ] spec thumbnail size to 250x250

*stretch criteria*
- [ ] Set up multiple sizes of thumbnails for different media types. This will eventually become a responsive app and building in this capability sooner rather than latter would be great. 
This may help:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=15438

**Comment by bglusman** [comment]
Yeah one line change to just replace 100x100 with 250x250 that seems good enough for now I'll PR that later or you can, trivial :-)

**Comment by komizutama** [comment]
Yeah I'm not worried. Just wanted to put all the information in one spot so I 1) didn't forget and 2) didn't have to dig through our slack convos to find it. heh
