### ISSUE TITLE
Guest can remove item from the cart. 

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#42]
Guest can delete an item/adjust quantity this quantity is released back into the general inventory

## Acceptance Criteria
- [ ] A guest can reduce the amount of an item that is in their order. 
- [ ] When they do so that quantity is released back into the available invnetory

**Comment by komizutama** [comment]
Hey  @bglusman this is done I believe no?

**Comment by bglusman** [comment]
Yup, though not from the cart tab only from the food/meal Rab it came from

**Comment by bglusman** [comment]
Er, tab, on phone :-)
