### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#7]
User accounts are created and stored in a database. Information is updatable and relational. ie family members can link their accounts and pool resources. Children under a certain age (What do St john's bread and life and West side coalition use?) are on their parents account.

**Comment by bglusman** [comment]
Oh, this is a change from current implementation, and from last discussion I recall...  so we want every individual adult to have an individual account, except children who will be a head count on some particular family member?  I guess the kids part could be considered implemented as is via the "family_members" count (idea being when we distribute monthly credits to a user, we will multiply by family member count, or apply a formula based on it), but linking accounts/pooling credits is an interesting/complicated question...  is it an automatic transfer to a single user, or a 2 way auth, that allows either user to pull from the other users credits?  We might want to defer this to a future iteration, if needed, as it adds a fair amount of complixity, and I'm uncertain of need/benefit if we support (and need to support) the family members logic also (which is simpler in any case).  Limiting scope is the best way to acheive product success :-)

**Comment by bglusman** [comment]
Closing this as partly done partly superceded by #167
