### ISSUE TITLE
Remove/fix  Back/settings and logout button

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#75]
<img width="680" alt="screen shot 2017-04-28 at 4 39 41 pm" src="https://cloud.githubusercontent.com/assets/4823357/25546499/5d86760a-2c31-11e7-949a-173cbf424689.png">

**Comment by komizutama** [comment]
Remove "back" and "settings buttons"

"logout button as well unless it is functional

**Comment by bglusman** [comment]
@komizutama I think this is done right?  I'm closing, reopen and/or clarify if disagree, back button is functional now (wasn't before) do you still want removed?
